env:
  browser: true
  jquery: true
  node: true

globals:

extends: 'eslint:recommended'

rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
